web/main.js:
	cd ../web && make build/main.js && cp build/main.js ../go/web/main.js

web/toolkit/bundle.js:
	cd ../toolkit && yarn build && cp dist/bundle.js ../go/web/toolkit/bundle.js

.PHONY: web/main.js web/toolkit/bundle.js
