name: Immediate Demo CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - name: Build Example Docker Image
        working-directory: demo/go-app
        run: make build-docker

      # https://github.com/google-github-actions/auth#setting-up-workload-identity-federation
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/454055752992/locations/global/workloadIdentityPools/immediate-demo-pool/providers/default-provider"
          service_account: "immediate-demo-deploy@snapper-326913.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: Push image
        working-directory: demo/go-app
        run: |-
          gcloud auth configure-docker -q
          docker build -t gcr.io/snapper-326913/immediate_demo:latest -f Dockerfile ../..
          docker push gcr.io/snapper-326913/immediate_demo:latest

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v0"
        with:
          project_id: snapper-326913
          image_url: "gcr.io/snapper-326913/immediate_demo:latest"
          working_directory: "demo/go-app"
