name: Immediate

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build Go
        working-directory: go
        run: go build -v ./...

      - name: Test Go
        working-directory: go
        run: go test -v ./...

      - name: Build Example Docker Image
        working-directory: go
        run: make build-examples-docker
